#ifndef SOFTWARERASTERIZER_H
#define SOFTWARERASTERIZER_H

#include "Framebuffer.h"
#include "Sprite.h"
#include <vector>
#include <string>
#include <QPoint>

/**
 * @file SoftwareRasterizer.h
 * @brief Pure Software Rasterizer implementing fundamental Computer Graphics Lab algorithms.
 * 
 * Strict CG Lab Rules adhered to:
 * - NO vector rendering libraries (No QPainter paths, No SVG, No OpenGL vector pipelines).
 * - Every line is generated by Bresenham's Integer Line Algorithm (all 8 octants).
 * - Every circle is generated by the Midpoint Circle Algorithm (8-way symmetry).
 * - Every ellipse is generated by the Midpoint Ellipse Algorithm (2 regions).
 * - Filled shapes use the Scanline Polygon Fill Algorithm.
 * - Sprites are blitted via pixel buffer matrix copy with color keying & alpha blending.
 * - Text is drawn using a 5x7 bitmap matrix font.
 */
class SoftwareRasterizer {
public:
    explicit SoftwareRasterizer(Framebuffer& framebuffer);

    Framebuffer& framebuffer() { return m_fb; }
    const Framebuffer& framebuffer() const { return m_fb; }

    // Core Primitives (Textbook CG Lab Algorithms)
    void setPixel(int x, int y, uint32_t color);
    uint32_t getPixel(int x, int y) const { return m_fb.getPixel(x, y); }

    // Bresenham's Line Algorithm (All 8 octants, integer arithmetic)
    void drawLineBresenham(int x0, int y0, int x1, int y1, uint32_t color);
    void drawDottedLineBresenham(int x0, int y0, int x1, int y1, uint32_t color, int dotPeriod = 6);
    void drawThickLineBresenham(int x0, int y0, int x1, int y1, int thickness, uint32_t color);

    // Xiaolin Wu's Anti-Aliased Line Algorithm (Sub-pixel intensity weighting)
    void drawLineXiaolinWu(int x0, int y0, int x1, int y1, uint32_t color);
    void drawLineAuto(int x0, int y0, int x1, int y1, uint32_t color);
    void setAntiAliasing(bool enabled) { m_useAntiAliasing = enabled; }
    bool isAntiAliasing() const { return m_useAntiAliasing; }

    // Midpoint Circle Algorithm (8-way symmetry, decision variable P_k = 1 - r)
    void drawCircleMidpoint(int xc, int yc, int r, uint32_t color);
    void fillCircleMidpoint(int xc, int yc, int r, uint32_t color);

    // Midpoint Ellipse Algorithm (Region 1 and Region 2)
    void drawEllipseMidpoint(int xc, int yc, int rx, int ry, uint32_t color);
    void fillEllipseMidpoint(int xc, int yc, int rx, int ry, uint32_t color);

    // Rectangles & Scanline Fills
    void drawRectBresenham(int x, int y, int w, int h, uint32_t color);
    void fillRectScanline(int x, int y, int w, int h, uint32_t color);

    // General Scanline Polygon Fill (Edge intersection, sorting, parity spans)
    void fillPolygonScanline(const std::vector<QPoint>& vertices, uint32_t color);

    // Sprite Blitting Engine (Bit-blit, color-key transparency, alpha blending)
    void blitSprite(const Sprite& sprite, int destX, int destY, bool flipH = false, float alpha = 1.0f);
    void blitSpriteScaled(const Sprite& sprite, int destX, int destY, int scaleX, int scaleY, bool flipH = false);

    // 2D Affine Transformation (Software Raster Rotation via Inverse Mapping)
    void blitSpriteRotated(const Sprite& sprite, int destCenterX, int destCenterY, float angleDegrees, float alpha = 1.0f);

    // Discrete 5x7 Pixel Font Rendering
    void drawCharBitmap(int x, int y, char c, uint32_t color, int scale = 1);
    void drawTextBitmap(int x, int y, const std::string& text, uint32_t color, int scale = 1);

    // Raster Post-Processing Filters
    void applyScanlines(float intensity = 0.25f);
    void applyInvert();
    void applyRadialVignette(int cx, int cy, int innerR, int outerR, float maxDarkness = 0.75f);

    // Lab Inspector / Debug Highlight Mode
    void setInspectorHighlight(bool enable) { m_inspectorHighlight = enable; }
    bool isInspectorHighlight() const { return m_inspectorHighlight; }

    // Real-Time CG Lab Telemetry
    struct Telemetry {
        uint32_t bresenhamLines{0};
        uint32_t xiaolinWuLines{0};
        uint32_t midpointCircles{0};
        uint32_t midpointEllipses{0};
        uint32_t scanlineFills{0};
        uint32_t spriteBlits{0};
        uint32_t rotatedSprites{0};
        uint64_t totalPixels{0};

        void reset() {
            bresenhamLines = 0;
            xiaolinWuLines = 0;
            midpointCircles = 0;
            midpointEllipses = 0;
            scanlineFills = 0;
            spriteBlits = 0;
            rotatedSprites = 0;
            totalPixels = 0;
        }
    };

    const Telemetry& telemetry() const { return m_telemetry; }
    void resetTelemetry() { 
        m_telemetry.reset(); 
        m_fb.resetTelemetry();
    }

private:
    Framebuffer& m_fb;
    bool m_inspectorHighlight{false};
    bool m_useAntiAliasing{false};
    Telemetry m_telemetry;

    // Internal scanline horizontal span helper
    inline void drawHorizontalSpan(int x0, int x1, int y, uint32_t color) {
        if (y < 0 || y >= m_fb.height()) return;
        if (x0 > x1) std::swap(x0, x1);
        int startX = std::max(0, x0);
        int endX = std::min(m_fb.width() - 1, x1);
        if (endX < startX) return;

        uint8_t a = (color >> 24) & 0xFF;
        if (a == 255) {
            for (int x = startX; x <= endX; ++x) {
                m_fb.setPixelUnsafe(x, y, color);
            }
        } else if (a > 0) {
            for (int x = startX; x <= endX; ++x) {
                m_fb.setPixelBlend(x, y, color);
            }
        }
        m_telemetry.totalPixels += (endX - startX + 1);
    }
};

#endif // SOFTWARERASTERIZER_H
